pull_request_rules:
  - name: Automatic merge for Actions
    conditions:
      - author=dependabot[bot]
      - or:
        - label=dependabot:actions
        - label=github_actions
      - or:
          - label=auto:dependabot
          - label=dependencies
    actions:
      merge:
        method: rebase
      label:
        add:
          - auto:mergify
  - name: Automatic merge for Composer patches
    conditions:
      - author=dependabot[bot]
      - or:
        - label=dependabot:php
        - label=php
      - or:
        - label=auto:dependabot
        - label=dependencies
      - dependabot-update-type=version-update:semver-patch
    actions:
      merge:
        method: rebase
      label:
        add:
          - auto:mergify
  - name: Automatic merge for JS patches
    conditions:
      - author=dependabot[bot]
      - or:
        - label=dependabot:javascript
        - label=javascript
      - or:
        - label=auto:dependabot
        - label=dependencies
      - dependabot-update-type=version-update:semver-patch
    actions:
      merge:
        method: rebase
      label:
        add:
          - auto:mergify